# Generated by Django 6.0.5 on 2026-05-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=5)),
                ('companyName', models.CharField(max_length=25)),
            ],
        ),
    ]
