# Generated by Django 6.0.5 on 2026-05-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_quizz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizz',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
