# Generated by Django 6.0.5 on 2026-05-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_quizz_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='leaderboard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=25)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
    ]
