# Generated by Django 6.0.5 on 2026-05-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_leaderboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='userWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=25)),
                ('wallet', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='score',
            field=models.IntegerField(),
        ),
    ]
